# -*- coding: utf-8 -*-
"""assignment_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxwobnhvcpH26JTafdZLvZe2ERtj9RG4

## Assignment #3 – Python Practice

**Name:** Escarlet Gabriel Vicente

**Course:** DATA 602 – M.S. Data Science

**Instructor:** Professor Schettini

Q1: Write a program that prompts the user for a meal: breakfast, lunch, or dinner. Then using if statements and else statements print the user a message recommending a meal. For example, if the meal was breakfast, you could say something like, “How about some bacon and eggs?”
"""

meal = input("Enter a meal (breakfast, lunch, or dinner): ").lower()

if meal == "breakfast":
    print("How about some bacon and eggs?")
elif meal == "lunch":
    print("Maybe a sandwich and soup would be nice.")
elif meal == "dinner":
    print("How about pasta or grilled chicken?")
else:
    print("Meal not recognized.")

"""Q2: The mailroom has asked you to design a simple payroll program that calculates a student employee’s gross pay, including any overtime wages. If any employee works over 20 hours in a week, the mailroom pays them 1.5 times their regular hourly pay rate for all hours over 20. You should take in the user’s input for the number of hours worked, and their rate of pay."""

hours = float(input("Enter hours worked: "))
rate = float(input("Enter hourly pay rate: "))

if hours > 20:
    overtime = hours - 20
    gross_pay = (20 * rate) + (overtime * rate * 1.5)
else:
    gross_pay = hours * rate

print(f"Gross pay: ${gross_pay:.2f}")

"""Q3: Write a function named times_ten. The function should accept an argument and display the product of its argument multiplied times 10."""

def times_ten(number):
    print(number * 10)

times_ten(5)

"""SQ4: Find the errors, debug the program, and then execute to show the output.



```
def main()
      Calories1 = input( "How many calories are in the first food?")
      Calories2 = input( "How many calories are in the first food?")
      showCalories(calories1, calories2)

def showCalories()   
   print(“The total calories you ate today”, format(calories1 + calories2,.2f))
```


"""

def main():
    calories1 = float(input("How many calories are in the first food? "))
    calories2 = float(input("How many calories are in the second food? "))
    showCalories(calories1, calories2)

def showCalories(calories1, calories2):
    print("The total calories you ate today:", format(calories1 + calories2, ".2f"))

main()

"""**The errors were fixed by adding missing colons, correcting variable names, defining parameters properly, and calling the main function.**

Q5: Write a program that uses any loop (while or for) that calculates the total of the following series of numbers:
1/30 + 2/29 + 3/28 ............. + 30/1
"""

total = 0

for i in range(1, 31):
    total += i / (31 - i)

print(total)

"""Q6: Write a function that computes the area of a triangle given its base and height.

The formula for an area of a triangle is:
AREA = 1/2 * BASE * HEIGHT
"""

def triangle_area(base, height):
    area = 0.5 * base * height
    print(area)

triangle_area(5, 4)