# -*- coding: utf-8 -*-
"""assignment_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QHgXFtZxTjC2EJnDHku6DRMG-E37vKs

## Assignment #2 – Python Practice

**Name:** Escarlet Gabriel Vicente

**Course:** DATA 602 – M.S. Data Science

**Instructor:** Professor Schettini

Q1. What will the following code display? Can you debug and fix the output?

```
numbers = [1, 2, 3, 4, 5]
print(numbers[1:-5])
```
Can you debug and fix the output? The code should return the entire list
"""

numbers = [1, 2, 3, 4, 5]
print(numbers[:])

"""**The original code returns an empty list because the slice numbers[1:-5] creates an invalid range.**

**To return the entire list, the slice was corrected to numbers[:], which prints all elements in the list**

Q2. Design a program that asks the user to enter a store’s sales for each day of the week. The amounts should be stored in a list. Use a loop to calculate the total sales for the week and display the result.
"""

sales = []
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

for day in days:
    amount = float(input(f"Enter sales for {day}: "))
    sales.append(amount)

total_sales = 0
for amount in sales:
    total_sales += amount

print(f"Total sales for the week: ${total_sales:.2f}")

"""Q3. Create a list with at least 5 places you’d like to travel to. Make sure the list isn’t in alphabetical order"""

places = ["Tokyo", "Barcelona", "New York", "Cape Town", "Rome"]

print("Original order:")
print(places)

places.sort()
print("Alphabetical order:")
print(places)

places.sort(reverse=True)
print("Reverse alphabetical order:")
print(places)

"""Q4. Write a program that creates a dictionary containing course numbers and the room numbers of the rooms where the courses meet. The program should also create a dictionary containing course numbers and the names of the instructors that teach each course. After that, the program should let the user enter a course number, then it should display the course’s room number, instructor, and meeting time."""

course_rooms = {
    "DATA602": "Room 315",
    "DATA606": "Room 210",
    "DATA607": "Room 402"
}

course_instructors = {
    "DATA602": "Professor Schettini",
    "DATA606": "Professor Catlin",
    "DATA607": "Professor Lui"
}

course_times = {
    "DATA602": "Monday 6:00 PM",
    "DATA606": "Wednesday 6:00 PM",
    "DATA607": "Thursday 6:00 PM"
}

course = input("Enter a course number: ")

if course in course_rooms:
    print("Room:", course_rooms[course])
    print("Instructor:", course_instructors[course])
    print("Meeting Time:", course_times[course])
else:
    print("Course not found.")

"""Q5. Write a program that keeps names and email addresses in a dictionary as key-value pairs. The program should then demonstrate the four options:

● look up a person’s email address,

● add a new name and email address,

● change an existing email address, and

● delete an existing name and email address.

"""

emails = {
    "Alice": "alice@email.com",
    "Bob": "bob@email.com",
    "Carol": "carol@email.com"
}

name = input("Enter a name to look up: ")
print(emails.get(name, "Name not found"))

new_name = input("Enter a new name: ")
new_email = input("Enter the email address: ")
emails[new_name] = new_email

change_name = input("Enter a name to change the email: ")
if change_name in emails:
    emails[change_name] = input("Enter the new email: ")

delete_name = input("Enter a name to delete: ")
emails.pop(delete_name, None)

print("Updated email list:")
print(emails)