# -*- coding: utf-8 -*-
"""assignment_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMl8R-8y5NnF2WMHOxCD9UGWOZhreD8l

## Assignment #1

**Name:** Escarlet Gabriel Vicente

**Course:** DATA 602 – M.S. Data Science

**Instructor:** Professor Schettini

# Q1
"""

numbers = [10, 20, 30, 40, 50]
print(numbers[:])

"""# Q2"""

sales = []

days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

for day in days:
    amount = float(input(f"Enter sales for {day}: "))
    sales.append(amount)

total = sum(sales)

print("Q2 Output: Total sales for the week:", total)

"""# Q3"""

places = ["Japan", "Brazil", "Iceland", "Morocco", "Canada"]

print("Q3 Output - Original list:", places)

places.sort()
print("Q3 Output - Sorted list:", places)

places.sort(reverse=True)
print("Q3 Output - Reverse sorted list:", places)

"""# Q4"""

course_rooms = {
    "CS101": "Room 3004",
    "CS102": "Room 4501",
    "CS103": "Room 6755"
}

course_instructors = {
    "CS101": "Dr. Smith",
    "CS102": "Prof. Allen",
    "CS103": "Dr. Johnson"
}

course_times = {
    "CS101": "8:00 AM",
    "CS102": "10:00 AM",
    "CS103": "2:00 PM"
}

course = "CS101"

print("Q4 Output - Room:", course_rooms[course])
print("Q4 Output - Instructor:", course_instructors[course])
print("Q4 Output - Time:", course_times[course])